services:
  # Memcached for storing rate-limits data.
  memcached:
    image: memcached:latest
    container_name: 1min-relay-memcached
    networks:
      - 1min-relay-network
    restart: unless-stopped
    # Does not require to expose port. Only used for internal communication.

  # 1min-relay
  1min-relay:
    image: kagzaz/1min-relay:latest
    container_name: 1min-relay-container
    ports:
      - "5001:5001"
    networks:
      - 1min-relay-network
    depends_on:
      - memcached
    environment:
      # Optional: Set a global API Key for the relay. 
      # If set, clients don't need to provide a Bearer token.
      - ONE_MIN_API_KEY=${ONE_MIN_API_KEY:-YOUR_API_KEY_HERE}
      # Use comma-separated string for permitted models
      - SUBSET_OF_ONE_MIN_PERMITTED_MODELS=${SUBSET_MODELS:-mistral-nemo,gpt-4o-mini,deepseek-chat}
      # Set to "True" to only allow models in the subset list above
      - PERMIT_MODELS_FROM_SUBSET_ONLY=${SUBSET_ONLY:-False}
    restart: unless-stopped
    labels:
      - "net.unraid.docker.managed=console"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/google/material-design-icons/master/png/action/settings_input_component/materialicons/48dp/1x/baseline_settings_input_component_black_48dp.png"
      - "net.unraid.docker.webui=http://[IP]:[PORT:5001]/"
      - "net.unraid.docker.shell=bash"

networks:
  1min-relay-network:
    name: 1min-relay-network
